---
title: "Writing Functions"
author: "Matthew Parker"
date: "10/24/19"
output: github_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(rvest)
library(patchwork)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


## Get started

We're going to write some functions.

Here's z scores
```{r}
x = rnorm(n = 30, mean = 4, sd = 2.3)
x_again = rnorm(n = 30, mean = 6, sd = 0.3)

(x - mean(x)) / sd(x)
(x_again - mean(x_again)) / sd(x_again)
```

Now a function.

```{r}
z_score = function(x) {
  
  if (!is.numeric(x)) {
    stop("x should be numeric")
  } else if (length(x) < 3) {
    stop("x should be longer than 3")
  }
  
  (x - mean(x)) / sd(x)
  
}
```

Try out the function

```{r, error = TRUE}
z_score(x = x_again)

z_score(x = 3)
z_score(x = "my name is jeff")
z_score(x = c(TRUE, TRUE, FALSE, TRUE))
z_score(x = iris)
```

## Multiple outputs

```{r}
mean_and_sd = function(input_x) {
  
  if (!is.numeric(input_x)) {
    stop("x should be numeric")
  } else if (length(input_x) < 3) {
    stop("x should be longer than 3")
  }
  
  list(
    mean_input = mean(input_x),
    sd_input = sd(input_x),
    z_score = (input_x - mean(input_x)) / sd(input_x)
  )
}
```

Test this function

```{r}
mean_and_sd(input_x = x_again)
```


## Multiple inputs



